name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-format:
    name: Run Linters & Formatters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install Dependencies (Poetry + requirements.txt)
        run: |
          poetry install --no-interaction --no-root
          pip install -r requirements.txt

      - name: Run Black
        run: poetry run black --check .

      - name: Run Flake8
        run: poetry run flake8 --max-line-length=88 --ignore=W291,W503,F401,F402,E712 .

      - name: Run Pylint
        run: poetry run pylint --max-line-length=88 --disable=R0917,W0611,C0325,R0912,W0621,W0631,W0603,E0213,R0801,C0103,C0411,C0412,W0613,R0913,R0914,R0915,W0707 app/

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint-format
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install Dependencies (Poetry + requirements.txt)
        run: |
          poetry install --no-interaction --no-root
          pip install -r requirements.txt

      - name: Run Tests
        run: poetry run pytest tests/

  docker-check:
    name: Check Docker Syntax & Build Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        run: docker run --rm -i hadolint/hadolint < Dockerfile

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Run Docker Container
        run: docker run --rm myapp:latest echo "Container runs fine"
